"use client";

import React from "react";
import { 
  ShieldCheck, 
  HeartHandshake, 
  Award, 
  Sparkles,
  Users2
} from "lucide-react";

export default function AboutUs() {
  const values = [
    {
      icon: <ShieldCheck className="h-6 w-6 text-primary" />,
      title: "Patient Confidentiality",
      desc: "We prioritize patient privacy with advanced data protection protocols complying with international medical regulations."
    },
    {
      icon: <HeartHandshake className="h-6 w-6 text-primary" />,
      title: "Compassionate Care",
      desc: "Our medical practitioners prioritize active listening and empathy to provide customized patient healthcare plans."
    },
    {
      icon: <Award className="h-6 w-6 text-primary" />,
      title: "Clinical Excellence",
      desc: "We select senior consultants with verified credentials and extensive experience inside renowned national hospitals."
    },
    {
      icon: <Sparkles className="h-6 w-6 text-primary" />,
      title: "Innovative Technology",
      desc: "We employ modern remote video calls, dashboard notifications, and digital records generators for seamless care."
    }
  ];

  return (
    <>
      <div className="bg-slate-50 dark:bg-slate-950 py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-16">
          
          {/* Hero Header */}
          <div className="text-center max-w-3xl mx-auto space-y-4">
            <span className="bg-primary/10 text-primary text-[10px] font-bold px-3 py-1 rounded-full uppercase tracking-wider">
              About CarePulse
            </span>
            <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
              Bridging the Gap Between Patients & Trusted Medical Care
            </h1>
            <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
              CarePulse is a premium clinical management system engineered to give patients rapid, safe, and direct consultation channels with certified doctors, without the standard overhead of waiting rooms and queues.
            </p>
          </div>

          {/* Visual Grid / Card */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center bg-white dark:bg-slate-900 rounded-3xl p-6 sm:p-10 border border-slate-150 dark:border-slate-800 shadow-xs">
            <div className="space-y-6">
              <h2 className="text-2xl font-bold text-slate-950 dark:text-white">
                Our Digital Healthcare Vision
              </h2>
              <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                Founded in 2026, CarePulse started as an initiative to bring remote consultation tools directly to patients during emergencies. Over the years, we have expanded our system to support complete patient profiles, medical report archives, digital prescriptions, and direct Stripe billing.
              </p>
              <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                By enabling doctors to claim scheduling blocks generated by administrators and linking them seamlessly to patient slots, CarePulse has reduced scheduling overhead by over 60%, allowing physicians to focus entirely on patient consultations.
              </p>
              
              <div className="flex gap-6 pt-4 border-t border-slate-100 dark:border-slate-800">
                <div>
                  <span className="block text-2xl font-extrabold text-primary">99.8%</span>
                  <span className="text-[10px] text-slate-400 uppercase tracking-wider font-semibold">Consultation Success</span>
                </div>
                <div>
                  <span className="block text-2xl font-extrabold text-primary">15 Mins</span>
                  <span className="text-[10px] text-slate-400 uppercase tracking-wider font-semibold">Average Response Time</span>
                </div>
              </div>
            </div>

            <div className="relative rounded-2xl overflow-hidden shadow-lg border border-slate-100 dark:border-slate-700 h-80 lg:h-[400px]">
              <img
                src="https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=400"
                alt="Medical Laboratory"
                className="w-full h-full object-cover"
              />
            </div>
          </div>

          {/* Core Values */}
          <div className="space-y-12">
            <div className="text-center max-w-2xl mx-auto space-y-2">
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white">Our Core Pillars</h2>
              <p className="text-xs text-slate-500">The philosophies driving CarePulse healthcare portal.</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              {values.map((val, idx) => (
                <div key={idx} className="bg-white dark:bg-slate-900 border border-slate-150 dark:border-slate-800 p-6 rounded-2xl shadow-xs space-y-4 hover:shadow-md transition-all">
                  <div className="p-3 bg-primary/5 rounded-xl inline-block">
                    {val.icon}
                  </div>
                  <h3 className="font-bold text-sm text-slate-900 dark:text-white">{val.title}</h3>
                  <p className="text-xs text-slate-500 leading-relaxed dark:text-slate-400">{val.desc}</p>
                </div>
              ))}
            </div>
          </div>

        </div>
      </div>
    </>
  );
}
